server:
  port: 8080

logging:
  level:
    root: INFO
    com.tenco.spring_blog: DEBUG    #우리 코드는 DEBUG이상까지

spring:
  #데이터 베이스 연결 (H2 메모리 DB 사용 )
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # H2 콘솔 화면 켜기 (http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true

  # JPA 설정
  jpa:
    hibernate:
      #시작할 떄마다 테이블을 새로 만듭니다. 기존 데이터는 다지워진다(개발용)
      ddl-auto: create
      #실행되는 sql을 콘솔에 촐력합니다
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_ssql: true # 출력되는 sql을 콘솔창에 줄바꿈해 보기좋게 표시
        #추후 data.sql을 테이블 생성 후에 실행합니다
    defer-datasource-initialization: true

  #서버 시작시 이 파일 실행
  sql:
    init:
      mode: always  # MYSQL 사용사 설정
      data-locations:
        - classpath:db/data.sql

